apiVersion: app/v1
kind: Deployment
metadata:
  name: vertex-deploy
  labels:
    app: myvertexapp1
spec:
  replicas: 3
  selector:
      matchLabels:
         app: myvertexapp1
  template:
     metadata:
       labels: 
         app: myvertexapp1
     spec:
       containers:
        - name: myvertexapp-container
          image:  nbktechnosys/myverteximage10mar23:1
          ports:
            - containerPort: 8080